version: '3.9'

services:
  backend:
    build: ./backend
    container_name: neurosync-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: neurosync-frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: neurosync-db
    restart: always
    environment:
      POSTGRES_DB: neurosync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: neurosync-redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: neurosync-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@neurosync.ai
      PGADMIN_DEFAULT_PASSWORD: neurosync123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
