# .github/workflows/triage.yml
name: 🤖 Issue Triage

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue content
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || '';
            const labels = context.payload.issue.labels.map(l => l.name);

            // Auto comment based on label
            if (labels.includes('bug')) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for reporting this bug! A team member will review it shortly. Please include reproduction steps and logs if possible.'
              });
            }

            if (labels.includes('feature')) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '🚀 Thanks for the feature suggestion! Let’s explore this together. Feel free to elaborate on your use case.'
              });
            }
